export const GET_SERVERS_REQUEST = `SERVER.GET_SERVERS_REQUEST`;
export const GET_SERVERS_SUCCESS = `SERVER.GET_SERVERS_SUCCESS`;
export const GET_SERVERS_FAILURE = `SERVER.GET_SERVERS_FAILURE`;
export const CLEAR_SERVERS = `SERVER.CLEAR_SERVERS`;
