export const USER_AUTH_PENDING = 'USER_AUTH_PENDING';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAILED = 'USER_AUTH_FAILED';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const RETRIEVED_DATA = 'RETRIEVED_DATA';
export const RETRIEVE_DATA_FAILED = 'RETRIEVE_DATA_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';
