export const LOGIN_REQUESTED = "LOGIN_REQUESTED";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_CLEAR_ERROR = "LOGIN_CLEAR_ERROR";
export const LOGOUT = "LOGOUT";

export const SERVER_LIST_REQUESTED = "SERVER_LIST_REQUESTED";
export const SERVER_LIST_RECEIVED = "SERVER_LIST_RECEIVED";
export const SERVER_LIST_NOT_RECEIVED = "SERVER_LIST_NOT_RECEIVED";
