export default {
  LOGIN_REQUESTED: "LOGIN_REQUESTED",
  LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_CLEAR_ERROR: "LOGIN_CLEAR_ERROR",
  LOGOUT: "LOGOUT",

  SERVER_LIST_REQUESTED: "SERVER_LIST_REQUESTED",
  SERVER_LIST_RECEIVED: "SERVER_LIST_RECEIVED",
  SERVER_LIST_NOT_RECEIVED: "SERVER_LIST_NOT_RECEIVED"
};
