export const SET_RESULTS_START = "SET_RESULTS_START";
export const SET_RESULTS_SUCCESS = "SET_RESULTS_SUCCESS";
export const SET_RESULTS_FAIL = "SET_RESULTS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";





