import { NAME } from './constants';

export const REQUEST_SERVERS = `${NAME}.REQUEST_SERVERS`;
export const REQUEST_SERVERS_SUCCESS = `${NAME}.REQUEST_SERVERS_SUCCESS`;
export const REQUEST_SERVERS_FAILURE = `${NAME}.REQUEST_SERVERS_FAILURE`;
