export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const SET_AUTHENTICATED_TO_TRUE = 'SET_AUTHENTICATED_TO_TRUE';
