export const AUTH_LOGIN_REQUESTED = 'AUTH_LOGIN_REQUESTED';
export const AUTH_LOGOUT_REQUESTED = 'AUTH_LOGOUT_REQUESTED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_ERROR_DISMISS = 'AUTH_ERROR_DISMISS';

export const SERVER_LIST_REQUESTED = 'SERVER_LIST_REQUESTED';
export const SERVER_LIST_RECEIVED = 'SERVER_LIST_RECEIVED';
export const SERVER_LIST_ERROR = 'SERVER_LIST_ERROR';
