export const LOGIN_ACTION_TYPES = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_PENDING: 'LOGIN_PENDING',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT'
};

export const SERVER_FETCH_ACTION_TYPES = {
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_PENDING: 'FETCH_PENDING',
    FETCH_FAIL: 'FETCH_FAIL'
};

export const SERVER_ERROR_TYPES = {
    INVALID_CREDENTIALS: 'invalidCredentials',
    UNKNOWN: 'unknown'
};
