const NAMESPACE = 'AUTHENTICATION';

export const INIT = `${NAMESPACE}/INIT`;
export const INIT_LOGOUT = `${NAMESPACE}/INIT_LOGOUT`;
export const SET_TOKEN = `${NAMESPACE}/SET_TOKEN`;
export const INIT_TOKEN_STORAGE = `${NAMESPACE}/INIT_TOKEN_STORAGE`;
export const AUTH_REQUEST = `${NAMESPACE}/AUTH_REQUEST`;
export const AUTH_SUCCESS = `${NAMESPACE}/AUTH_SUCCESS`;
export const AUTH_FAILURE = `${NAMESPACE}/AUTH_FAILURE`;
