export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_SERVERS_LIST_REQUEST = 'GET_SERVERS_LIST_REQUEST';
export const GET_SERVERS_LIST_SUCCESS = 'GET_SERVERS_LIST_SUCCESS';
export const GET_SERVERS_LIST_FAILURE = 'GET_SERVERS_LIST_FAILURE';
