export const FAKE_DATA = [
  { "name": "Lithuania #34", "distance": 137 },
  { "name": "Lithuania #74", "distance": 174 },
  { "name": "Latvia #74", "distance": 50 },
  { "name": "Germany #36", "distance": 163 },
  { "name": "Lithuania #18", "distance": 48 },
  { "name": "Lithuania #76", "distance": 127 },
  { "name": "Lithuania #75", "distance": 54 },
  { "name": "Lithuania #47", "distance": 95 },
  { "name": "Singapore #38", "distance": 120 },
  { "name": "United States #92", "distance": 131 },
  { "name": "Japan #59", "distance": 67 },
  { "name": "Germany #89", "distance": 27 },
  { "name": "Lithuania #26", "distance": 142 },
  { "name": "Lithuania #26", "distance": 176 },
  { "name": "Germany #68", "distance": 190 },
  { "name": "Japan #79", "distance": 86 },
  { "name": "Lithuania #93", "distance": 31 },
  { "name": "United States #42", "distance": 137 },
  { "name": "Singapore #75", "distance": 158 },
  { "name": "Japan #46", "distance": 190 },
  { "name": "Japan #26", "distance": 66 },
  { "name": "United States #85", "distance": 178 },
  { "name": "Japan #75", "distance": 73 },
  { "name": "United Kingdom #100", "distance": 57 },
  { "name": "United Kingdom #68", "distance": 99 },
  { "name": "United States #84", "distance": 50 },
  { "name": "Lithuania #26", "distance": 141 },
  { "name": "Lithuania #98", "distance": 63 },
  { "name": "Germany #100", "distance": 99 },
  { "name": "Japan #34", "distance": 184 }
]