export const LOGIN_IN_PROCESS = "LOGIN_IN_PROCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SET_USERNAME = "SET_USERNAME";
export const SET_PASSWORD = "SET_PASSWORD";
export const AUTH_SERVER_ERROR = "AUTH_SERVER_ERROR";

export const SERVERS_LOADED = "SERVERS_LOADED";
export const SERVERS_LOADING = "SERVERS_LOADING";
export const SERVERS_SERVER_ERROR = "SERVERS_SERVER_ERROR";
export const SERVERS_SORT_BY_SERVER = "SERVERS_SORT_BY_SERVER";
export const SERVERS_SORT_BY_DISTANCE = "SERVERS_SORT_BY_DISTANCE";
