const ACTION_PREFIX = 'SERVERS';

export const FETCH_SERVERS = `${ACTION_PREFIX}/FETCH_SERVERS`;
export const LOADING = `${ACTION_PREFIX}/LOADING`;
export const FETCH_ERROR = `${ACTION_PREFIX}/FETCH_ERROR`;
