export default {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    GET_SERVERS: 'GET_SERVERS',
    GET_SERVERS_FAILURE: 'GET_SERVERS_FAILURE',
    SORT_DISTANCE: 'SORT_DISTANCE',
    SORT_NAME: 'SORT_NAME',
    LOGOUT: 'LOGOUT'
};
