export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const SERVERS_REQUEST = 'SERVERS_REQUEST';
export const SERVERS_SUCCESS = 'SERVERS_SUCCESS';
